mod 'boxen', '1.1.1', :github_tarball => 'boxen/puppet-boxen'
mod 'stdlib', '3.0.0', :github_tarball => "puppetlabs/puppetlabs-stdlib"
mod 'homebrew', '1.1.2', :github_tarball => 'boxen/puppet-homebrew'
